name: Maven Library Snapshot

on:
  push:
    branches:
      - main
      - LTS/*
      - hotfix/*
  workflow_dispatch:

jobs:
  snapshot:
    uses: zepben/.github/.github/workflows/maven-lib-snapshot.yml@main
    with:
      private: false
    secrets: inherit
