name: Maven Library Snapshot

on:
  push:
    branches:
      - main
      - LTS/*
  workflow_dispatch:

jobs:
  run:
    uses: zepben/.github/.github/workflows/maven-lib-snapshot.yml@main
    with:
      private: false
      product-key: "test-utils-jvm"
      product-repo: "zepben/test-utils-jvm"
    secrets: inherit
